### ISSUE TITLE
支持搜索

### ISSUE THREAD

**Issue by dirichy** [rainzm/flash-zh.nvim#1]
有可能支持搜索地跳转吗

**Comment by rainzm** [comment]
现在应该就算是搜索跳转吧，如果没有label，可以不断的输入，和搜索差不多。不知道你说的搜索是什么意思呢？

**Comment by dirichy** [comment]
就是斜杠和问号那个搜索

**Comment by rainzm** [comment]
目前简单基于flash.nvim的好像不大行，从其 Readme 查到的 / 以及 ？搜索的配置：
<img width="741" alt="image" src="https://github.com/rainzm/flash-zh.nvim/assets/22927169/a2836989-ef5e-4b8b-a581-38fd5229000c">
这里的mode好像无法更改。

不过理论上应该是可以，毕竟思路就是匹配前做一次转换。

**Comment by Leiyi548** [comment]
可以自己改下 flash.nvim 的源码，把 没有区配项的时候自动关闭给取消掉。
