### ISSUE TITLE
汉字以"zh", "ch", "sh"开头的均无标识

### ISSUE THREAD

**Issue by HeraPtt** [rainzm/flash-zh.nvim#11]
映射的快捷键为<c-s>
搜索关键字z, c, s或者zh, ch, sh

**Comment by rainzm** [comment]
这个项目目前只支持小鹤双拼。

**Comment by HeraPtt** [comment]
> 这个项目目前只支持小鹤双拼。

了解，刚查了下，zh,ch,sh分别对应v,i,u。这样也可以用哈
谢谢啦，插件做的很棒

**Comment by rainzm** [comment]
是的，谢谢你的肯定。
