### ISSUE TITLE
好像不支持zh,ch,sh的识别

### ISSUE THREAD

**Issue by JensynLo** [rainzm/flash-zh.nvim#12]
我使用的是 vscode-neovim, 问题如下
<img width="152" alt="image" src="https://github.com/user-attachments/assets/6934e344-4d56-415e-b296-8c677ee7e6fd">
当我按下 's' 后, 拼音开头是 sh 的 "社" (社区) 并没有显示跳转
这是我的 [配置](https://github.com/TyrannosaurusLjx/NvChad/blob/main/vscode_init.lua#L50)

**Comment by rainzm** [comment]
目前这个项目只支持小鹤双拼，在小鹤双拼里面，sh 对应的是 u。
