### ISSUE TITLE
大佬你好,我做了一下 虎码 的table , 不知道大佬是否有计划做多词库的支持

### ISSUE THREAD

**Issue by shinonomeow** [rainzm/flash-zh.nvim#13]
https://github.com/shininome/flash-zh.nvim/blob/main/lua/flash-zh/hu.lua

**Comment by rainzm** [comment]
之前有人基于此项目做了虎码的支持，他开了一个新项目，你看看是否满足你的需求呢：
https://github.com/Leiyi548/flash-zhh.nvim

**Comment by shinonomeow** [comment]
> 之前有人基于此项目做了虎码的支持，他开了一个新项目，你看看是否满足你的需求呢： https://github.com/Leiyi548/flash-zhh.nvim

太感动了, 我去试试

**Comment by rainzm** [comment]
可能后面新加的中英混用没有支持，如果有需要你可以试着添加。
