### ISSUE TITLE
偶尔不生效

### ISSUE THREAD

**Issue by qinjianwei** [rainzm/flash-zh.nvim#14]
![image](https://github.com/user-attachments/assets/0a4cf621-7b55-4b07-b645-ffc00e61f22e)
我输入me，没有定位到么
![image](https://github.com/user-attachments/assets/b399edaf-df74-4129-818c-2d44f72c22dc)
插件也是加载了的

**Comment by rainzm** [comment]
上面的例子中，期望是定位到什么？
另外可以发一下你的此插件配置嘛？

**Comment by qinjianwei** [comment]
me定位到么
return {
  {
    "rainzm/flash-zh.nvim",
    event = "VeryLazy",
    dependencies = "folke/flash.nvim",
    keys = {
      {
        "s",
        mode = { "n", "x", "o" },
        function()
          require("flash-zh").jump({
            chinese_only = false,
          })
        end,
        desc = "Flash between Chinese",
      },
    },
  },
  {
    "folke/flash.nvim",
    event = "VeryLazy",
    opts = {
      highlight = {
        backdrop = false,
        matches = false,
      },
    },
  },
}

**Comment by qinjianwei** [comment]
我输入me的时候应该定位到“么”

配置是

```lua
return {
  {
    "rainzm/flash-zh.nvim",
    event = "VeryLazy",
    dependencies = "folke/flash.nvim",
    keys = {
      {
        "s",
        mode = { "n", "x", "o" },
        function()
          require("flash-zh").jump({
            chinese_only = false,
          })
        end,
        desc = "Flash between Chinese",
      },
    },
  },
  {
    "folke/flash.nvim",
    event = "VeryLazy",
    opts = {
      highlight = {
        backdrop = false,
        matches = false,
      },
    },
  },
}
```

**Comment by rainzm** [comment]
我这边搞了个简单的例子是可以定位到"么"的，能不能将你的例子完整以文字的方式发出来，我在自己这边尝试一下，你是用 s 触发搜索的嘛？

**Comment by qinjianwei** [comment]
我的意思不是定位不到么。我的意思是他偶尔定位不到任何中文字符串。偶尔他又好啦

**Comment by qinjianwei** [comment]
是用s触发的，用fw触发提示
![image](https://github.com/user-attachments/assets/f30cb907-4e3a-4db7-ab21-ebc6b780e575)

**Comment by rainzm** [comment]
leap-zh 不是我这个插件，我的这个叫作 flash-zh，是基于 flash.nvim 的。

**Comment by qinjianwei** [comment]
我使用s触发，搜索的时候偶尔也不能搜索中文

**Comment by rainzm** [comment]
好的，我会再看一下，如果你有稳定复现或者较高频率复现的用例，随时可以告诉我。

**Comment by qinjianwei** [comment]
现在复现了，我需要怎么做？

**Comment by rainzm** [comment]
把你相关的文字copy过来吧，然后是光标在什么位置以及搜索什么 都发一下吧

**Comment by qinjianwei** [comment]
[10.1.3 栈和参数.md](https://github.com/user-attachments/files/17811228/10.1.3.md)文件发你啦，中文全搜不起来。但是我感觉和文本内容没用什么关系，有时候重新打开又可以啦

**Comment by qinjianwei** [comment]
刚才第二次打开又可以搜索啦

**Comment by rainzm** [comment]
这个文件里面好像只有三个字，你的leap-zh 以及 leap.nvim 禁用了吗？

**Comment by qinjianwei** [comment]
我没有安装leap.vim

**Comment by qinjianwei** [comment]
![image](https://github.com/user-attachments/assets/7ec9e0fb-5aaa-498f-91e5-0ac3fa625529)
这是我jx家在的所有插件

**Comment by rainzm** [comment]
我试了很多次，没有复现过。项目应该在你的本地，~/.local/share/nvim/lazy/flash-zh.nvim 下，你有需要的话可以稍微阅读一下代码，在合适的地方使用 print 添加日志，如果你对代码有任何疑问，可以随时问我。

**Comment by qinjianwei** [comment]
没有写过neovim插件，请问print的日志在哪里能看到呀？

**Comment by rainzm** [comment]
`:messages` 可以看
