### ISSUE TITLE
feat 请求添加 remote 操作

### ISSUE THREAD

**Issue by Leiyi548** [rainzm/flash-zh.nvim#2]
在 flash.nvim 默认是 r 快捷键，然后可以用来 remote 操作，我感觉加一个 remote 蛮好的。

**Comment by rainzm** [comment]
```lua
{
  "rainzm/flash-zh.nvim",
  event = "VeryLazy",
  dependencies = "folke/flash.nvim",
  keys = {
    {
      "r",
      mode = { "n", "x", "o" },
      function()
        require("flash-zh").jump({
          search = { wrap = false },
          remote_op = {
	    restore = true,
	    motion = true,
          },
        })
      end,
    },
  },
},

```
是不是像上面这样自己映射一下也能实现？

**Comment by Leiyi548** [comment]
> ```lua
> {
>   "rainzm/flash-zh.nvim",
>   event = "VeryLazy",
>   dependencies = "folke/flash.nvim",
>   keys = {
>     {
>       "r",
>       mode = { "n", "x", "o" },
>       function()
>         require("flash-zh").jump({
>           search = { wrap = false },
>           remote_op = {
> 	    restore = true,
> 	    motion = true,
>           },
>         })
>       end,
>     },
>   },
> },
> ```
> 
> 是不是像上面这样自己映射一下也能实现？

是的
