### ISSUE TITLE
能不能让 label 支持小写字母

### ISSUE THREAD

**Issue by Leiyi548** [rainzm/flash-zh.nvim#3]
能不能让 label 支持小写字母，我现在自己用的是数字，也考虑过大写字母（可是大写字母按 shift 多了，小拇指会疼），请问能实现小写字母当做 label 吗？

**Comment by rainzm** [comment]
我是把纯英文的跳转和中文跳转分开使用的，所以使用频率不高，倒还好。

应该是可以实现的，是核心问题就是：获取每个匹配项需要排除的字母label；不知道是否需要 flash.nvim 额外的支持，等有空我研究一下。

**Comment by Leiyi548** [comment]
> 我是把纯英文的跳转和中文跳转分开使用的，所以使用频率不高，倒还好。
> 
> 应该是可以实现的，是核心问题就是：获取每个匹配项需要排除的字母label；不知道是否需要 flash.nvim 额外的支持，等有空我研究一下。

我也是把中文跳转和英文跳转分开，不过我是想要双手都在主键区，按 shift 或者按数字都会有一点点卡的感觉，全是小写字母就最爽了，flash.nvIm 好像能自己设置 label。

**Comment by Leiyi548** [comment]
> 我是把纯英文的跳转和中文跳转分开使用的，所以使用频率不高，倒还好。
> 
> 应该是可以实现的，是核心问题就是：获取每个匹配项需要排除的字母label；不知道是否需要 flash.nvim 额外的支持，等有空我研究一下。

看了下是这个函数 
![image](https://github.com/rainzm/flash-zh.nvim/assets/76139422/4f68e26d-b5b2-4e01-b06c-f338ecc92f37)

**Comment by rainzm** [comment]
确实，赋值labeler函数就可以实现，可以参考默认的 [labeler](https://github.com/folke/flash.nvim/blob/48817af25f51c0590653bbc290866e4890fe1cbe/lua/flash/labeler.lua#L17) 实现，其中的重点在于 [skip](https://github.com/folke/flash.nvim/blob/48817af25f51c0590653bbc290866e4890fe1cbe/lua/flash/labeler.lua#L162) 函数，它可以给出windows下能用的 [labels](https://github.com/folke/flash.nvim/blob/48817af25f51c0590653bbc290866e4890fe1cbe/lua/flash/labeler.lua#L182)：一一获取匹配项目的上下文，将下文将要出现的 char 从labels中排除出去。

看上去，每个匹配项都有可用的label集合，而是对于整个window有一个可用的label集合。

等用空，我可以试试实现一版本，你也可以尝试实现。

**Comment by rainzm** [comment]
确实，通过labeler函数应该可以实现，我的大致想法是（可能对于中英混杂的会有些问题）：
1. 通过 match.win, match.pos 以及 match.end_pos 获取匹配项的内容再额外加后面一个字符组合成 context。
2. 通过python包pypinyin将上述 context 翻译成全拼拼音，再转换成双拼拼音 pattern。
3. 从上述 pattern 中去除键盘的输入内容（这个应该在 state 里面），剩下的第一个字符就是应该排除的 label: excludeLabel。
4. 从剩下的 labels 中去除 excludeLabel 后为 match 分配一个 label。

等周末我会尝试实现一下，你也可以试试实现一下。

**Comment by Leiyi548** [comment]
> 确实，通过labeler函数应该可以实现，我的大致想法是（可能对于中英混杂的会有些问题）：
> 
> 1. 通过 match.win, match.pos 以及 match.end_pos 获取匹配项的内容再额外加一个字符组合成 context。
> 2. 通过python包pypinyin将上述 context 翻译成全拼拼音，再转换成双拼拼音 pattern。
> 3. 从上述 pattern 中去除键盘的输入内容（这个应该在 state 里面），剩下的第一个字符就是应该排除的 label: excludeLabel。
> 4. 从剩下的 labels 中去除 excludeLabel 后为 match 分配一个 label。
> 
> 等周末我会尝试实现一下，你也可以试试实现一下。

好的，我也会试一试

**Comment by rainzm** [comment]
计算match对应excludeLabel的想法是ok的，但是同一个window下matches的excludeLabel应该是共享的，所以可以参考默认的 [labeler](https://github.com/folke/flash.nvim/blob/48817af25f51c0590653bbc290866e4890fe1cbe/lua/flash/labeler.lua#L17)实现，其中 [skip](https://github.com/folke/flash.nvim/blob/48817af25f51c0590653bbc290866e4890fe1cbe/lua/flash/labeler.lua#L162) 函数用来过滤掉那些 excludeLabels，重点是 [这里](https://github.com/folke/flash.nvim/blob/48817af25f51c0590653bbc290866e4890fe1cbe/lua/flash/labeler.lua#L182)。

**Comment by rainzm** [comment]
尝试了一下，思路是没错的，但是遇到一些问题，主要是lua中utf8字符的处理，这个好像得依赖luautf8库；有些复杂。暂时如果想要使用小写字母可以这样配置：
```lua
return {
	{
		"rainzm/flash-zh.nvim",
		event = "VeryLazy",
		dependencies = "folke/flash.nvim",
		keys = {
			{
				"s",
				mode = { "n", "x", "o" },
				function()
					require("flash-zh").jump({labels = "asdfghjklqwertyuiopzxcvbnm"})
				end,
				desc = "Flash between Chinese",
			},
		},
	},
	{
		"folke/flash.nvim",
		event = "VeryLazy",
		opts = {
			highlight = {
				backdrop = false,
				matches = false,
			},
		},
    }
}
```
如果遇到无法匹配的问题，（在中英混杂的环境中概率高），可以先到达指定行，再匹配。

**Comment by rainzm** [comment]
@Leiyi548 你好，我尝试实现了对于小写 label  的支持，通过自定义labeler，避免了小写label和拼音的冲突，你可以试试，实现有些粗糙，先等待下你的反馈。

**Comment by Leiyi548** [comment]
> @Leiyi548 你好，我尝试实现了对于小写 label 的支持，通过自定义labeler，避免了小写label和拼音的冲突，你可以试试，实现有些粗糙，先等待下你的反馈。

我也实现了，主要还是用你的代码，我用的输入方案是虎码，这是我的 github 地址 https://github.com/Leiyi548/flash-zhh.nvim/commit/c40867ff0f304a15149412fb914ff0b72eaa61b4，忘 fork 你了（十分抱歉）。

**Comment by Leiyi548** [comment]
https://github.com/Leiyi548/flash-zhh.nvim/commit/c40867ff0f304a15149412fb914ff0b72eaa61b4
