### ISSUE TITLE
BUG: 未知原因的崩溃

### ISSUE THREAD

**Issue by dirichy** [rainzm/flash-zh.nvim#6]
![IMG_4726](https://github.com/rainzm/flash-zh.nvim/assets/144102919/1f5deb27-c0d3-4451-8287-f194465f9705)
![IMG_4724](https://github.com/rainzm/flash-zh.nvim/assets/144102919/0b707e45-886f-4a99-96f0-7a6ad76a4357)
在此文件中搜索句号得到一个崩溃，neovim的界面卡死。
报错是labeler中，怀疑是因为有一个句号在行末所以没有下一位导致的空值错误。

**Comment by rainzm** [comment]
触发bug的键盘按键是什么？

**Comment by dirichy** [comment]
进入jump模式后我按了 ”.” 来搜索句号，然后就出现了bug。此外别的按键也偶尔出现bug，猜测是labeler对下一个按键的不同情况没有处理好

**Comment by rainzm** [comment]
我在自己这里没有复现，你能不能把你那边能触发bug的文件，脱敏后发我一份，我试试。

**Comment by dirichy** [comment]
发现一个稳定触发的方式，当屏幕中有“。\”时搜索“。”一定会崩溃

**Comment by dirichy** [comment]
\documentclass{ctexart}

\begin{document}
test 。\
\end{document}

**Comment by dirichy** [comment]
\documentclass{ctexart}

\begin{document}
test 。\\
\end{document}

**Comment by dirichy** [comment]
这个文件在我这边搜句号是会出现bug的，你试试看你能否复现

**Comment by rainzm** [comment]
复现了，我找下问题。

**Comment by dirichy** [comment]
好的，太感谢了。

**Comment by rainzm** [comment]
已经解决，可以试试，另外增加了对 `\` 这种需要转义的字符的支持。

**Comment by dirichy** [comment]
好的，谢谢
