### ISSUE TITLE
Bug: 对多音字没有处理。

### ISSUE THREAD

**Issue by dirichy** [rainzm/flash-zh.nvim#9]
如果出现label的位置的下一个字是多音字，并没有过滤掉其全部读音。
最小工作示例：

番茄番茄番茄番茄番茄番茄番茄

搜索qp后会出现f这个label，所以不能继续搜索fj。

**Comment by rainzm** [comment]
没有复现呢：
![Kapture 2024-06-29 at 23 26 19](https://github.com/rainzm/flash-zh.nvim/assets/22927169/e69accbb-8b7b-44dc-b00c-2ee0ca1dc2d8)

**Comment by rainzm** [comment]
搜索q的时候有f，但是 qp 之后就没有 f 了。

**Comment by dirichy** [comment]
![截图 2024-06-30 10-54-32](https://github.com/rainzm/flash-zh.nvim/assets/144102919/6a18fcfd-7c56-4e56-8c7d-97f7dc82eb7c)
奇怪了，我这边是有这个问题的。可能和多音字遍历顺序也有关，我看了你的代码，应该是最后一个被遍历的音会保留。我弄一个各种遍历顺序都能出现的情况给你复现吧

**Comment by dirichy** [comment]
试试

会会会会会会会会会会会会会会会会会会会会

这个字有两个音，hv和kk。你搜一下hv看看h会不会出现在label中，如果没有出现的话看看k有没有出现。

**Comment by dirichy** [comment]
我目前的想法是字查音的反向表改成table而不是字符串，遍历的时候对每种可能都排除在label之外，但是我不太熟悉labeler的写法，正在看api

**Comment by rainzm** [comment]
@dirichy 我增加了对多音字的处理，用空可以试试是否有问题。

**Comment by cycode0527** [comment]
已切换旧版本测试，确实如此：
![image](https://github.com/rainzm/flash-zh.nvim/assets/76815699/083ca942-2385-4dd0-8a0c-aae16e9de5fa)
![image](https://github.com/rainzm/flash-zh.nvim/assets/76815699/24999313-533f-4325-9a25-0cfb4b1ad766)
之所以切回旧版本，是因为新版本有严重问题在我电脑上，所以暂时不切，我先找找自己原因看看啥情况

**Comment by cycode0527** [comment]
目前我所谓的问题是这样的：
![image](https://github.com/rainzm/flash-zh.nvim/assets/76815699/beb25748-7bbb-4286-98a8-67cba2676191)
输入s后按下任意一个键，比如说f, 就报错，然后nvim就炸了，出现非常多诡异问题完全无法正常使用。暂时不提issue

**Comment by rainzm** [comment]
我刚在我这边没有复现，旧版本没有问题嘛？因为这个 tbl_filter 函数的调用没有修改，你的neovim版本是什么呢？

**Comment by cycode0527** [comment]
> 我刚在我这边没有复现，旧版本没有问题嘛？因为这个 tbl_filter 函数的调用没有修改，你的neovim版本是什么呢？

是的，我也想知道为什么会这样，甚至我手动替换了两个更新文件也发生同样的问题。
```
NVIM v0.10.0
Build type: Release
LuaJIT 2.1.1713484068
Run "nvim -V1 -v" for more info
```

**Comment by cycode0527** [comment]
因为在我这里是 100% 出问题，所以很难给出准确的复现。我也不知道为什么会发生这样的情况。我在另一个 #6 看到有类似的情况，但是具体原因应该是完全不一样的

**Comment by rainzm** [comment]
flash 有更新到最新嘛？

**Comment by cycode0527** [comment]
> flash 有更新到最新嘛？

flash 是最新的 43f6 commit 。neovim 用的也是最新的 0.10.0

**Comment by dirichy** [comment]
已解决，请查看我的pr

**Comment by cycode0527** [comment]
> 已解决，请查看我的pr

非常感谢，你的 pr 没有问题，请求合并，我这里先手动更新了
